### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by Maiyourathaan** [jorgealmerio/ProfileFromPoints#1]
This plug-in cannot be installed in new QGIS version 3.26, is it a Bug?

**Comment by jorgealmerio** [comment]
Yes, you are right! I will check it as soon as possible!

**Comment by KjeldH1973** [comment]
Hello Jorge, Is there a solution for use profilefrompoints in QGIS version 3.26 or later.

**Comment by jorgealmerio** [comment]
Fixed in version 3.2.
Thanks!
